### ISSUE TITLE
Readme-Datei des Gesamtrepositoriums nicht korrekt angelegt

### ISSUE THREAD

**Issue by ameun541** [Bbsteiger/BdK6.5.3_P3_SoSe2021_Bettina_Steiger#1]
Ich glaube dir ist bei der Erstellung der Readme-Datei für das Gesamtrepositorium ein Fehler unterlaufen. Die Endung der Datei ist nicht .md und die Darstellung des Textes ist anders, als bei der anderen Readme-Datei.

**Comment by Bbsteiger** [comment]
Ja stimmt danke.
